import { allValidationCases as existingRegressionCases } from '../engine-validation-v01/cases'
import type { SeraVNextEngineSourceType } from '../../../frontend/src/lib/sera-vnext/engine-contract'

export type EngineV02AxisName = 'perception' | 'objective' | 'action'

export type EngineV02Expected =
  | {
      kind: 'code'
      axis: EngineV02AxisName
      code: string
    }
  | {
      kind: 'abstention'
    }
  | {
      kind: 'notCode'
      axis: EngineV02AxisName
      code: string
    }

export type EngineV02ValidationCase = {
  caseId: string
  title: string
  group: 'independent_accuracy' | 'leaf_reachability_positive' | 'leaf_reachability_negative'
  locale: 'pt-BR' | 'en'
  sourceType: SeraVNextEngineSourceType
  narrative: string
  expected: EngineV02Expected
  tags: string[]
}

export const leafReachabilityPositiveCases: EngineV02ValidationCase[] = [
  {
    caseId: 'V02-LEAF-P-A-EN',
    title: 'Perception adequate assessment no failure',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The pilot recognized the deviation in time and identified the warning correctly before acting.',
    expected: { kind: 'code', axis: 'perception', code: 'P-A' },
    tags: ['leaf:P-A', 'en', 'no-failure'],
  },
  {
    caseId: 'V02-LEAF-P-B-EN',
    title: 'Perception sensory limitation',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The pilot did not see the runway because poor visibility and fog degraded visual cues.',
    expected: { kind: 'code', axis: 'perception', code: 'P-B' },
    tags: ['leaf:P-B', 'en'],
  },
  {
    caseId: 'V02-LEAF-P-C-EN',
    title: 'Perception knowledge limitation',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The pilot did not perceive the situation because of a training knowledge gap and lack of knowledge.',
    expected: { kind: 'code', axis: 'perception', code: 'P-C' },
    tags: ['leaf:P-C', 'en'],
  },
  {
    caseId: 'V02-LEAF-P-D-PT',
    title: 'Perception attention pressure',
    group: 'leaf_reachability_positive',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'O piloto treinado tinha instrumentos disponíveis mas não percebeu o desvio por distração e pressão de tempo.',
    expected: { kind: 'code', axis: 'perception', code: 'P-D' },
    tags: ['leaf:P-D', 'pt-BR'],
  },
  {
    caseId: 'V02-LEAF-P-E-EN',
    title: 'Perception time management pressure',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The trained pilot had available instruments but did not recognize the deviation because of urgency and schedule pressure.',
    expected: { kind: 'code', axis: 'perception', code: 'P-E' },
    tags: ['leaf:P-E', 'en'],
  },
  {
    caseId: 'V02-LEAF-P-F-EN',
    title: 'Perception ambiguous information',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The trained pilot had capability and available instruments but did not perceive the state; information was ambiguous and misleading.',
    expected: { kind: 'code', axis: 'perception', code: 'P-F' },
    tags: ['leaf:P-F', 'en'],
  },
  {
    caseId: 'V02-LEAF-P-G-EN',
    title: 'Perception information available correct',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The trained pilot had capability but did not perceive the state; information was available and correct.',
    expected: { kind: 'code', axis: 'perception', code: 'P-G' },
    tags: ['leaf:P-G', 'en'],
  },
  {
    caseId: 'V02-LEAF-P-H-EN',
    title: 'Perception information unavailable',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The trained pilot had capability but did not identify the state; no warning and missing information were present.',
    expected: { kind: 'code', axis: 'perception', code: 'P-H' },
    tags: ['leaf:P-H', 'en'],
  },
  {
    caseId: 'V02-LEAF-O-A-PT',
    title: 'Objective conservative managed goal',
    group: 'leaf_reachability_positive',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'A tripulação descontinuou a aproximação e executou arremetida, preservando separação segura e risco foi gerenciado.',
    expected: { kind: 'code', axis: 'objective', code: 'O-A' },
    tags: ['leaf:O-A', 'pt-BR', 'no-failure'],
  },
  {
    caseId: 'V02-LEAF-O-B-PT',
    title: 'Objective routine violation with awareness',
    group: 'leaf_reachability_positive',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'A tripulação sabia da regra, estava consciente do alerta e deliberadamente optou por desviar como violação de rotina.',
    expected: { kind: 'code', axis: 'objective', code: 'O-B' },
    tags: ['leaf:O-B', 'pt-BR', 'violation-awareness'],
  },
  {
    caseId: 'V02-LEAF-O-C-EN',
    title: 'Objective exceptional violation with awareness',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The crew knew the rule, was aware of the warning, consciously chose to deviate in an exceptional violation.',
    expected: { kind: 'code', axis: 'objective', code: 'O-C' },
    tags: ['leaf:O-C', 'en', 'violation-awareness'],
  },
  {
    caseId: 'V02-LEAF-O-D-EN',
    title: 'Objective unmanaged risk',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The goal accepted risk to save time; the rule was followed but risk was not managed.',
    expected: { kind: 'code', axis: 'objective', code: 'O-D' },
    tags: ['leaf:O-D', 'en'],
  },
  {
    caseId: 'V02-LEAF-A-A-PT',
    title: 'Action adequate response',
    group: 'leaf_reachability_positive',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'O piloto qualificado executou arremetida; a ação foi correta e adequada.',
    expected: { kind: 'code', axis: 'action', code: 'A-A' },
    tags: ['leaf:A-A', 'pt-BR', 'no-failure'],
  },
  {
    caseId: 'V02-LEAF-A-B-EN',
    title: 'Action feedback implementation failure',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The crew action failed because readback failed and feedback was not checked.',
    expected: { kind: 'code', axis: 'action', code: 'A-B' },
    tags: ['leaf:A-B', 'en', 'feedback'],
  },
  {
    caseId: 'V02-LEAF-A-C-PT',
    title: 'Action slip/lapse implementation failure',
    group: 'leaf_reachability_positive',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'O piloto desceu abaixo do perfil inadvertidamente e não verificou a altitude.',
    expected: { kind: 'code', axis: 'action', code: 'A-C' },
    tags: ['leaf:A-C', 'pt-BR', 'A-A/A-C-boundary'],
  },
  {
    caseId: 'V02-LEAF-A-D-EN',
    title: 'Action physical capability limitation',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The pilot selected wrong mode but was unable physically due to an ergonomic limitation.',
    expected: { kind: 'code', axis: 'action', code: 'A-D' },
    tags: ['leaf:A-D', 'en'],
  },
  {
    caseId: 'V02-LEAF-A-E-PT',
    title: 'Action knowledge limitation',
    group: 'leaf_reachability_positive',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'O piloto selecionou modo errado por lacuna de conhecimento, treinamento e habilidade.',
    expected: { kind: 'code', axis: 'action', code: 'A-E' },
    tags: ['leaf:A-E', 'pt-BR'],
  },
  {
    caseId: 'V02-LEAF-A-F-EN',
    title: 'Action selection failed under time pressure',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The qualified pilot selected wrong mode during time pressure; no time to select the correct mode.',
    expected: { kind: 'code', axis: 'action', code: 'A-F' },
    tags: ['leaf:A-F', 'en'],
  },
  {
    caseId: 'V02-LEAF-A-G-PT',
    title: 'Action feedback failed under time pressure',
    group: 'leaf_reachability_positive',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'O piloto qualificado selecionou modo errado sob pressão de tempo; sem tempo para verificar feedback.',
    expected: { kind: 'code', axis: 'action', code: 'A-G' },
    tags: ['leaf:A-G', 'pt-BR'],
  },
  {
    caseId: 'V02-LEAF-A-H-EN',
    title: 'Action time management subtype',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The qualified pilot executed an incorrect action; time pressure and a late decision created urgency.',
    expected: { kind: 'code', axis: 'action', code: 'A-H' },
    tags: ['leaf:A-H', 'en'],
  },
  {
    caseId: 'V02-LEAF-A-I-PT',
    title: 'Action selection subtype',
    group: 'leaf_reachability_positive',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'O piloto qualificado selecionou modo errado e alinhou para a pista errada.',
    expected: { kind: 'code', axis: 'action', code: 'A-I' },
    tags: ['leaf:A-I', 'pt-BR'],
  },
  {
    caseId: 'V02-LEAF-A-J-EN',
    title: 'Action feedback subtype',
    group: 'leaf_reachability_positive',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The qualified pilot selected wrong mode; readback and feedback cross-check were involved.',
    expected: { kind: 'code', axis: 'action', code: 'A-J' },
    tags: ['leaf:A-J', 'en'],
  },
]

export const independentAccuracyCases: EngineV02ValidationCase[] = [
  {
    caseId: 'V02-INDEP-PT-HELI-PD',
    title: 'Offshore helicopter Portuguese perception under workload',
    group: 'independent_accuracy',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'Durante aproximação offshore ao helideck, o piloto treinado tinha instrumentos disponíveis mas não percebeu o desvio por distração, carga de trabalho e pressão de tempo.',
    expected: { kind: 'code', axis: 'perception', code: 'P-D' },
    tags: ['pt-BR', 'offshore-helicopter'],
  },
  {
    caseId: 'V02-INDEP-PT-HELI-OA',
    title: 'Offshore helicopter Portuguese safe go-around',
    group: 'independent_accuracy',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'Na aproximação offshore, a tripulação descontinuou e executou arremetida para preservar separação segura; o risco foi gerenciado.',
    expected: { kind: 'code', axis: 'objective', code: 'O-A' },
    tags: ['pt-BR', 'offshore-helicopter', 'no-failure'],
  },
  {
    caseId: 'V02-INDEP-PT-TECH-PH',
    title: 'Portuguese technical alert unavailable',
    group: 'independent_accuracy',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'O piloto treinado tinha capacidade mas não identificou o estado do sistema; sem alerta, informação ausente e indicação indisponível antes da ação.',
    expected: { kind: 'code', axis: 'perception', code: 'P-H' },
    tags: ['pt-BR', 'technical-dominant'],
  },
  {
    caseId: 'V02-INDEP-PT-VIOL-AWARE',
    title: 'Portuguese violation with explicit awareness',
    group: 'independent_accuracy',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'A tripulação sabia da regra, estava consciente do alerta e decidiu violar deliberadamente uma prática de rotina.',
    expected: { kind: 'code', axis: 'objective', code: 'O-B' },
    tags: ['pt-BR', 'violation-awareness'],
  },
  {
    caseId: 'V02-INDEP-PT-VIOL-NO-AWARE',
    title: 'Portuguese continuation without awareness must abstain',
    group: 'independent_accuracy',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'A tripulação continuou a aproximação instável, mas o texto não estabelece que conhecia a regra, percebeu o alerta ou desviou conscientemente.',
    expected: { kind: 'abstention' },
    tags: ['pt-BR', 'violation-awareness-boundary', 'insufficient-evidence'],
  },
  {
    caseId: 'V02-INDEP-PT-AC',
    title: 'Portuguese A-C boundary',
    group: 'independent_accuracy',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'O piloto desceu abaixo do perfil inadvertidamente e não verificou a altitude antes da consequência.',
    expected: { kind: 'code', axis: 'action', code: 'A-C' },
    tags: ['pt-BR', 'A-A/A-C-boundary'],
  },
  {
    caseId: 'V02-INDEP-PT-AA',
    title: 'Portuguese A-A no failure boundary',
    group: 'independent_accuracy',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'O piloto qualificado executou arremetida e a ação foi correta e adequada para preservar a separação segura.',
    expected: { kind: 'code', axis: 'action', code: 'A-A' },
    tags: ['pt-BR', 'A-A/A-C-boundary', 'no-failure'],
  },
  {
    caseId: 'V02-INDEP-PT-PFPM',
    title: 'Portuguese PF/PM multi-actor abstention',
    group: 'independent_accuracy',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'PF e PM discutiram a aproximação, mas o relato não identifica qual ator agiu no ponto de fuga nem qual percepção, objetivo ou ação falhou.',
    expected: { kind: 'abstention' },
    tags: ['pt-BR', 'PF/PM', 'multi-actor', 'insufficient-evidence'],
  },
  {
    caseId: 'V02-INDEP-PT-POST-TRAP',
    title: 'Portuguese post-escape consequence trap',
    group: 'independent_accuracy',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'Depois do impacto, o relatório descreveu dano e feridos. Antes disso, o texto não informa percepção, objetivo ou ação do ator direto.',
    expected: { kind: 'abstention' },
    tags: ['pt-BR', 'post-escape-trap', 'insufficient-evidence'],
  },
  {
    caseId: 'V02-INDEP-PT-HELI-AJ',
    title: 'Offshore helicopter Portuguese feedback action',
    group: 'independent_accuracy',
    locale: 'pt-BR',
    sourceType: 'synthetic',
    narrative: 'No voo offshore, o piloto qualificado selecionou modo errado; readback, feedback e checagem cruzada estavam envolvidos.',
    expected: { kind: 'code', axis: 'action', code: 'A-J' },
    tags: ['pt-BR', 'offshore-helicopter', 'feedback'],
  },
  {
    caseId: 'V02-INDEP-EN-HELI-PF',
    title: 'English offshore helicopter ambiguous helideck cues',
    group: 'independent_accuracy',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'During the offshore helicopter approach, the trained pilot had capability but did not perceive the state because helideck information was ambiguous and misleading.',
    expected: { kind: 'code', axis: 'perception', code: 'P-F' },
    tags: ['en', 'offshore-helicopter'],
  },
  {
    caseId: 'V02-INDEP-EN-TECH-PG',
    title: 'English technical information available',
    group: 'independent_accuracy',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The trained pilot had capability but did not perceive the state; the system information was available and correct.',
    expected: { kind: 'code', axis: 'perception', code: 'P-G' },
    tags: ['en', 'technical-dominant'],
  },
  {
    caseId: 'V02-INDEP-EN-TECH-AB',
    title: 'English technical feedback implementation failure',
    group: 'independent_accuracy',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The crew action failed because readback failed and the feedback verification was not checked after the action.',
    expected: { kind: 'code', axis: 'action', code: 'A-B' },
    tags: ['en', 'technical-dominant', 'feedback'],
  },
  {
    caseId: 'V02-INDEP-EN-OD',
    title: 'English unmanaged risk goal',
    group: 'independent_accuracy',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The operational goal accepted risk to save time; the rule was followed but the crew did not limit risk.',
    expected: { kind: 'code', axis: 'objective', code: 'O-D' },
    tags: ['en'],
  },
  {
    caseId: 'V02-INDEP-EN-VIOL-NO-AWARE',
    title: 'English continuation without awareness abstains',
    group: 'independent_accuracy',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The crew continued the unstable approach, but the text does not establish a known rule, warning awareness, or conscious deviation.',
    expected: { kind: 'abstention' },
    tags: ['en', 'violation-awareness-boundary', 'insufficient-evidence'],
  },
  {
    caseId: 'V02-INDEP-EN-PFPM',
    title: 'English PF/PM actor unresolved',
    group: 'independent_accuracy',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'PF and PM were both mentioned, but the narrative does not identify who acted at the escape point or which P/O/A axis failed.',
    expected: { kind: 'abstention' },
    tags: ['en', 'PF/PM', 'multi-actor', 'insufficient-evidence'],
  },
  {
    caseId: 'V02-INDEP-EN-POST-TRAP',
    title: 'English post-escape trap',
    group: 'independent_accuracy',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'After the collision there was damage and injury. Before that, the narrative gives no actor perception, goal, or action evidence.',
    expected: { kind: 'abstention' },
    tags: ['en', 'post-escape-trap', 'insufficient-evidence'],
  },
  {
    caseId: 'V02-INDEP-EN-AF',
    title: 'English action selection failed under pressure',
    group: 'independent_accuracy',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The qualified pilot selected wrong mode during time pressure; no time to select the correct mode.',
    expected: { kind: 'code', axis: 'action', code: 'A-F' },
    tags: ['en'],
  },
  {
    caseId: 'V02-INDEP-EN-OA',
    title: 'English no-failure managed go-around',
    group: 'independent_accuracy',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'The crew discontinued the approach, executed a go-around, preserved safe separation, and risk was managed.',
    expected: { kind: 'code', axis: 'objective', code: 'O-A' },
    tags: ['en', 'no-failure'],
  },
  {
    caseId: 'V02-INDEP-EN-HELI-AG',
    title: 'English offshore helicopter feedback pressure',
    group: 'independent_accuracy',
    locale: 'en',
    sourceType: 'synthetic',
    narrative: 'During the offshore helicopter approach, the qualified pilot selected wrong mode under time pressure; no time to verify feedback.',
    expected: { kind: 'code', axis: 'action', code: 'A-G' },
    tags: ['en', 'offshore-helicopter', 'feedback'],
  },
]

export const leafReachabilityNegativeCases: EngineV02ValidationCase[] = leafReachabilityPositiveCases.map((item) => {
  const expected = item.expected
  if (expected.kind !== 'code') throw new Error(`leaf positive case missing code expectation: ${item.caseId}`)
  return {
    caseId: `${item.caseId}-NEG`,
    title: `Negative control for ${expected.code}`,
    group: 'leaf_reachability_negative',
    locale: item.locale,
    sourceType: 'synthetic',
    narrative: 'The record contains administrative context only and does not establish actor perception, objective, action, or escape-point evidence.',
    expected: {
      kind: 'notCode',
      axis: expected.axis,
      code: expected.code,
    },
    tags: [`negative:${expected.code}`, item.locale],
  }
})

export const engineV02ValidationCases = [
  ...independentAccuracyCases,
  ...leafReachabilityPositiveCases,
  ...leafReachabilityNegativeCases,
]

export { existingRegressionCases }
