import type { SeraVNextLocale, SeraCanonicalQuestionTreeNode, CanonicalSeraAxis } from './types'

export const SERA_CANONICAL_TREE_MODEL_VERSION = 'A4R190-A_v0.2.0'

export const SERA_CANONICAL_TREE_NODES: readonly SeraCanonicalQuestionTreeNode[] = [
  {
    "nodeInventoryId": "A4R185-NINV-0001",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "O_ROOT",
    "axis": "O",
    "nodeOrder": 1,
    "exactQuestionTextPt": "O que o operador estava tentando alcançar? Qual era a intenção ou o objetivo que o levou a cometer o ato inseguro?",
    "exactQuestionTextEn": "What was the operator or crew member trying to achieve...what was the intent or goal(s) that led to the unsafe act?",
    "branchCondition": "START",
    "nextNodeHint": "NEXT_NODE:O_RULES",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "O_RULES",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0002",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "O_RULES",
    "axis": "O",
    "nodeOrder": 2,
    "exactQuestionTextPt": "O objetivo era consistente com as regras, regulamentos e procedimentos operacionais estabelecidos e também era consistente com um bom gerenciamento de riscos?",
    "exactQuestionTextEn": "Was the GOAL consistent with rules, regulations and SOPs, and was it also consistent with good risk management?",
    "branchCondition": "SIM",
    "nextNodeHint": "NEXT_NODE:O_MANAGED_RISK",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "O_MANAGED_RISK",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0003",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "O_RULES",
    "axis": "O",
    "nodeOrder": 2,
    "exactQuestionTextPt": "O objetivo era consistente com as regras, regulamentos e procedimentos operacionais estabelecidos e também era consistente com um bom gerenciamento de riscos?",
    "exactQuestionTextEn": "Was the GOAL consistent with rules, regulations and SOPs, and was it also consistent with good risk management?",
    "branchCondition": "NÃO",
    "nextNodeHint": "NEXT_NODE:O_ROUTINE",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "O_ROUTINE",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0004",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "O_ROUTINE",
    "axis": "O",
    "nodeOrder": 3,
    "exactQuestionTextPt": "Violação de rotina?",
    "exactQuestionTextEn": "Routine violation?",
    "branchCondition": "SIM",
    "nextNodeHint": "LEAF:O-B",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "O-B",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0005",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "O_ROUTINE",
    "axis": "O",
    "nodeOrder": 3,
    "exactQuestionTextPt": "Violação de rotina?",
    "exactQuestionTextEn": "Routine violation?",
    "branchCondition": "NÃO",
    "nextNodeHint": "LEAF:O-C",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "O-C",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0006",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "O_MANAGED_RISK",
    "axis": "O",
    "nodeOrder": 4,
    "exactQuestionTextPt": "O ato inseguro resultou do exercício de uma meta que, embora consistente com as Regras e Regulamentos, não era consistente com os procedimentos operacionais estabelecidos ou não gerenciava ou limitava o risco?",
    "exactQuestionTextEn": "GOAL conservative, managed risk, consistent with SOPs?",
    "branchCondition": "SIM",
    "nextNodeHint": "LEAF:O-A",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "O-A",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0007",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "O_MANAGED_RISK",
    "axis": "O",
    "nodeOrder": 4,
    "exactQuestionTextPt": "O ato inseguro resultou do exercício de uma meta que, embora consistente com as Regras e Regulamentos, não era consistente com os procedimentos operacionais estabelecidos ou não gerenciava ou limitava o risco?",
    "exactQuestionTextEn": "GOAL conservative, managed risk, consistent with SOPs?",
    "branchCondition": "NÃO",
    "nextNodeHint": "LEAF:O-D",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "O-D",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0008",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_ROOT",
    "axis": "P",
    "nodeOrder": 1,
    "exactQuestionTextPt": "O que o operador acreditou que estava acontecendo no ambiente com relação ao objetivo que pretendia alcançar?",
    "exactQuestionTextEn": "What did the operator or crewmember believe was the state of the world with respect to the goal(s)?",
    "branchCondition": "START",
    "nextNodeHint": "NEXT_NODE:P_ASSESSMENT",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "P_ASSESSMENT",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0009",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_ASSESSMENT",
    "axis": "P",
    "nodeOrder": 2,
    "exactQuestionTextPt": "Avaliação correta ou adequada da situação?",
    "exactQuestionTextEn": "Correct or adequate assessment of the situation?",
    "branchCondition": "SIM",
    "nextNodeHint": "LEAF:P-A",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "P-A",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0010",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_ASSESSMENT",
    "axis": "P",
    "nodeOrder": 2,
    "exactQuestionTextPt": "Avaliação correta ou adequada da situação?",
    "exactQuestionTextEn": "Correct or adequate assessment of the situation?",
    "branchCondition": "NÃO",
    "nextNodeHint": "NEXT_NODE:P_CAPABILITY",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "P_CAPABILITY",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0011",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_CAPABILITY",
    "axis": "P",
    "nodeOrder": 3,
    "exactQuestionTextPt": "Possuía a capacidade necessária para sentir e perceber a situação?",
    "exactQuestionTextEn": "Had the pre-requisite capability to sense and perceive the situation?",
    "branchCondition": "NÃO_SENSORIAL",
    "nextNodeHint": "LEAF:P-B",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "P-B",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0012",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_CAPABILITY",
    "axis": "P",
    "nodeOrder": 3,
    "exactQuestionTextPt": "Possuía a capacidade necessária para sentir e perceber a situação?",
    "exactQuestionTextEn": "Had the pre-requisite capability to sense and perceive the situation?",
    "branchCondition": "NÃO_CONHECIMENTO",
    "nextNodeHint": "LEAF:P-C",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "P-C",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0013",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_CAPABILITY",
    "axis": "P",
    "nodeOrder": 3,
    "exactQuestionTextPt": "Possuía a capacidade necessária para sentir e perceber a situação?",
    "exactQuestionTextEn": "Had the pre-requisite capability to sense and perceive the situation?",
    "branchCondition": "SIM",
    "nextNodeHint": "NEXT_NODE:P_TIME_PRESSURE",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "P_TIME_PRESSURE",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0014",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_TIME_PRESSURE",
    "axis": "P",
    "nodeOrder": 4,
    "exactQuestionTextPt": "A pressão do tempo percebida era excessiva?",
    "exactQuestionTextEn": "Time pressure excessive?",
    "branchCondition": "SIM_ATENCAO",
    "nextNodeHint": "LEAF:P-D",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "P-D",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0015",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_TIME_PRESSURE",
    "axis": "P",
    "nodeOrder": 4,
    "exactQuestionTextPt": "A pressão do tempo percebida era excessiva?",
    "exactQuestionTextEn": "Time pressure excessive?",
    "branchCondition": "SIM_GERENCIAMENTO",
    "nextNodeHint": "LEAF:P-E",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "P-E",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0016",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_TIME_PRESSURE",
    "axis": "P",
    "nodeOrder": 4,
    "exactQuestionTextPt": "A pressão do tempo percebida era excessiva?",
    "exactQuestionTextEn": "Time pressure excessive?",
    "branchCondition": "NÃO",
    "nextNodeHint": "NEXT_NODE:P_INFORMATION_AMBIGUOUS",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "P_INFORMATION_AMBIGUOUS",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0017",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_INFORMATION_AMBIGUOUS",
    "axis": "P",
    "nodeOrder": 5,
    "exactQuestionTextPt": "A informação era ilusória ou ambígua?",
    "exactQuestionTextEn": "Information illusory or ambiguous?",
    "branchCondition": "SIM",
    "nextNodeHint": "LEAF:P-F",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "P-F",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0018",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_INFORMATION_AMBIGUOUS",
    "axis": "P",
    "nodeOrder": 5,
    "exactQuestionTextPt": "A informação era ilusória ou ambígua?",
    "exactQuestionTextEn": "Information illusory or ambiguous?",
    "branchCondition": "NÃO",
    "nextNodeHint": "NEXT_NODE:P_INFORMATION_AVAILABLE",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "P_INFORMATION_AVAILABLE",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0019",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_INFORMATION_AVAILABLE",
    "axis": "P",
    "nodeOrder": 6,
    "exactQuestionTextPt": "A informação estava disponível e correta?",
    "exactQuestionTextEn": "Information available and correct?",
    "branchCondition": "SIM",
    "nextNodeHint": "LEAF:P-G",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "P-G",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0020",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "P_INFORMATION_AVAILABLE",
    "axis": "P",
    "nodeOrder": 6,
    "exactQuestionTextPt": "A informação estava disponível e correta?",
    "exactQuestionTextEn": "Information available and correct?",
    "branchCondition": "NÃO",
    "nextNodeHint": "LEAF:P-H",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "P-H",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0021",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_ROOT",
    "axis": "A",
    "nodeOrder": 1,
    "exactQuestionTextPt": "Como o operador estava tentando atingir o objetivo?",
    "exactQuestionTextEn": "How was the operator trying to achieve the goal(s)?",
    "branchCondition": "START",
    "nextNodeHint": "NEXT_NODE:A_IMPLEMENTED",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "A_IMPLEMENTED",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0022",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_IMPLEMENTED",
    "axis": "A",
    "nodeOrder": 2,
    "exactQuestionTextPt": "A ação foi implementada como pretendida?",
    "exactQuestionTextEn": "Implemented as intended?",
    "branchCondition": "NÃO_DESLIZE_LAPSO_ERRO",
    "nextNodeHint": "LEAF:A-C",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "A-C",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0023",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_IMPLEMENTED",
    "axis": "A",
    "nodeOrder": 2,
    "exactQuestionTextPt": "A ação foi implementada como pretendida?",
    "exactQuestionTextEn": "Implemented as intended?",
    "branchCondition": "NÃO_FEEDBACK",
    "nextNodeHint": "LEAF:A-B",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "A-B",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0024",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_IMPLEMENTED",
    "axis": "A",
    "nodeOrder": 2,
    "exactQuestionTextPt": "A ação foi implementada como pretendida?",
    "exactQuestionTextEn": "Implemented as intended?",
    "branchCondition": "SIM",
    "nextNodeHint": "NEXT_NODE:A_CORRECT",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "A_CORRECT",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0025",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_CORRECT",
    "axis": "A",
    "nodeOrder": 3,
    "exactQuestionTextPt": "A ação foi a correta ou adequada?",
    "exactQuestionTextEn": "Correct or adequate?",
    "branchCondition": "SIM",
    "nextNodeHint": "LEAF:A-A",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "A-A",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0026",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_CORRECT",
    "axis": "A",
    "nodeOrder": 3,
    "exactQuestionTextPt": "A ação foi a correta ou adequada?",
    "exactQuestionTextEn": "Correct or adequate?",
    "branchCondition": "NÃO",
    "nextNodeHint": "NEXT_NODE:A_CAPABILITY",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "A_CAPABILITY",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0027",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_CAPABILITY",
    "axis": "A",
    "nodeOrder": 4,
    "exactQuestionTextPt": "O operador ou a tripulação possuía o pré-requisito de capacidade, conhecimento ou habilidades necessárias para formar e implementar uma ação apropriada para a situação?",
    "exactQuestionTextEn": "Had the pre-requisite capability to make a response?",
    "branchCondition": "NÃO_INABILIDADE",
    "nextNodeHint": "LEAF:A-D",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "A-D",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0028",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_CAPABILITY",
    "axis": "A",
    "nodeOrder": 4,
    "exactQuestionTextPt": "O operador ou a tripulação possuía o pré-requisito de capacidade, conhecimento ou habilidades necessárias para formar e implementar uma ação apropriada para a situação?",
    "exactQuestionTextEn": "Had the pre-requisite capability to make a response?",
    "branchCondition": "NÃO_CONHECIMENTO",
    "nextNodeHint": "LEAF:A-E",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "A-E",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0029",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_CAPABILITY",
    "axis": "A",
    "nodeOrder": 4,
    "exactQuestionTextPt": "O operador ou a tripulação possuía o pré-requisito de capacidade, conhecimento ou habilidades necessárias para formar e implementar uma ação apropriada para a situação?",
    "exactQuestionTextEn": "Had the pre-requisite capability to make a response?",
    "branchCondition": "SIM",
    "nextNodeHint": "NEXT_NODE:A_TIME_PRESSURE",
    "transitionKind": "NEXT_NODE",
    "nextNodeId": "A_TIME_PRESSURE",
    "leafCode": null,
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0030",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_TIME_PRESSURE",
    "axis": "A",
    "nodeOrder": 5,
    "exactQuestionTextPt": "A pressão do tempo era realmente excessiva?",
    "exactQuestionTextEn": "Time pressure excessive?",
    "branchCondition": "NÃO_SELECAO",
    "nextNodeHint": "LEAF:A-F",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "A-F",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0031",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_TIME_PRESSURE",
    "axis": "A",
    "nodeOrder": 5,
    "exactQuestionTextPt": "A pressão do tempo era realmente excessiva?",
    "exactQuestionTextEn": "Time pressure excessive?",
    "branchCondition": "NÃO_FEEDBACK",
    "nextNodeHint": "LEAF:A-G",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "A-G",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0032",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_TIME_PRESSURE",
    "axis": "A",
    "nodeOrder": 5,
    "exactQuestionTextPt": "A pressão do tempo era realmente excessiva?",
    "exactQuestionTextEn": "Time pressure excessive?",
    "branchCondition": "SIM_GERENCIAMENTO",
    "nextNodeHint": "LEAF:A-H",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "A-H",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0033",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_TIME_PRESSURE",
    "axis": "A",
    "nodeOrder": 5,
    "exactQuestionTextPt": "A pressão do tempo era realmente excessiva?",
    "exactQuestionTextEn": "Time pressure excessive?",
    "branchCondition": "SIM_SELECAO",
    "nextNodeHint": "LEAF:A-I",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "A-I",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  },
  {
    "nodeInventoryId": "A4R185-NINV-0034",
    "sourcePath": "docs/sera-vnext/SERA_ENGINE_VNEXT_CANONICAL_QUESTION_TREE_ASSET_A4R99_v0.2.0.md",
    "sourceStatus": "CANONICAL_QUESTION_TREE_ASSET",
    "nodeIdType": "TECHNICAL_STABLE_ID_NOT_ORIGINAL_SOURCE_ID",
    "nodeId": "A_TIME_PRESSURE",
    "axis": "A",
    "nodeOrder": 5,
    "exactQuestionTextPt": "A pressão do tempo era realmente excessiva?",
    "exactQuestionTextEn": "Time pressure excessive?",
    "branchCondition": "SIM_FEEDBACK",
    "nextNodeHint": "LEAF:A-J",
    "transitionKind": "LEAF",
    "nextNodeId": null,
    "leafCode": "A-J",
    "canonicalStatus": "CANONICAL_QUESTION_TREE_ASSET_ACTIVE",
    "usableForAxisDecision": true,
    "issueFlag": "NODE_ID_IS_TECHNICAL_STABLE",
    "notes": "technicalStableId, not original source id; notOriginalSourceId=true"
  }
]

export const SERA_CANONICAL_TREE_NODE_COUNT = SERA_CANONICAL_TREE_NODES.length

export const SERA_CANONICAL_TREE_AXIS_DISTRIBUTION = {
  P: SERA_CANONICAL_TREE_NODES.filter((node) => node.axis === 'P').length,
  O: SERA_CANONICAL_TREE_NODES.filter((node) => node.axis === 'O').length,
  A: SERA_CANONICAL_TREE_NODES.filter((node) => node.axis === 'A').length,
} as const

export const SERA_CANONICAL_TREE_NODE_IDS = SERA_CANONICAL_TREE_NODES.map((node) => node.nodeId)

export function getCanonicalNodeById(nodeId: string): SeraCanonicalQuestionTreeNode | null {
  return SERA_CANONICAL_TREE_NODES.find((node) => node.nodeId === nodeId) || null
}

export function listCanonicalNodesByAxis(axis: CanonicalSeraAxis): readonly SeraCanonicalQuestionTreeNode[] {
  return SERA_CANONICAL_TREE_NODES.filter((node) => node.axis === axis)
}

export function getCanonicalQuestionText(node: SeraCanonicalQuestionTreeNode, locale: SeraVNextLocale): string {
  return locale === 'pt-BR' ? node.exactQuestionTextPt : node.exactQuestionTextEn
}

export function isCanonicalNodeUsableForAxisDecision(node: SeraCanonicalQuestionTreeNode): boolean {
  return node.usableForAxisDecision && node.canonicalStatus === 'CANONICAL_QUESTION_TREE_ASSET_ACTIVE'
}

export function assertCanonicalTreeInventoryInvariants(): void {
  if (SERA_CANONICAL_TREE_NODE_COUNT !== 34) {
    throw new Error(`SERA canonical tree node count mismatch: expected 34, got ${SERA_CANONICAL_TREE_NODE_COUNT}`)
  }
  if (SERA_CANONICAL_TREE_AXIS_DISTRIBUTION.P !== 13 || SERA_CANONICAL_TREE_AXIS_DISTRIBUTION.O !== 7 || SERA_CANONICAL_TREE_AXIS_DISTRIBUTION.A !== 14) {
    throw new Error('SERA canonical tree axis distribution mismatch (expected P=13,O=7,A=14).')
  }
}
