export const SERA_VNEXT_ENGINE_VERSION = '0.2.0'
export const SERA_VNEXT_METHODOLOGY_VERSION = 'SERA_PT_V1_FROZEN'
export const SERA_VNEXT_BASELINE_ID = 'SERA_VNEXT_BASELINE_V0'
export const SERA_VNEXT_FIXTURE_SET_ID = 'SERA_VNEXT_FIXTURE_SET_V0'
