/** Nomes canônicos — espelha FAILURE_NAMES do Python. */
export const FAILURE_NAMES: Record<string, string> = {
  'P-A': 'Nenhuma Falha de Percepção',
  'P-B': 'Falha Sensorial',
  'P-C': 'Falha de Conhecimento/Percepção',
  'P-D': 'Falha de Atenção',
  'P-E': 'Falha no Gerenciamento do Tempo',
  'P-F': 'Falha de Percepção',
  'P-G': 'Falha de Atenção',
  'P-H': 'Falha de Comunicação',
  'O-A': 'Nenhuma Falha de Objetivo',
  'O-B': 'Violação Rotineira',
  'O-C': 'Falha de Intenção / Violação Excepcional',
  'O-D': 'Falha de Intenção (Não Violação)',
  'A-A': 'Nenhuma Falha de Ação',
  'A-B': 'Deslizes, Omissões e Lapsos',
  'A-C': 'Falha no Feedback da Execução',
  'A-D': 'Inabilidade para a Resposta',
  'A-E': 'Falha de Conhecimento/Decisão',
  'A-F': 'Falha na Seleção da Ação',
  'A-G': 'Falha de Feedback',
  'A-H': 'Falha no Gerenciamento do Tempo',
  'A-I': 'Falha na Seleção da Ação por Pressão do Tempo',
  'A-J': 'Falha de Feedback por Pressão do Tempo',
}
